GPT=$(HOME)/snap/bin/gpt

.DELETE_ON_ERROR:

FILENAME1 ?= S1C_IW_SLC__1SDH_20250604T154436_20250604T154503_002635_005742_B6BF.zip

all: $(FILENAME1).dim

# Split
target_split.dim: $(FILENAME1)
	$(GPT) TOPSAR-Split -Ssource=$(FILENAME1) -PfirstBurstIndex=2 -PlastBurstIndex=7 -Psubswath=IW2 -t target_split

# Orbital Params
target_orb.dim: target_split.dim
	$(GPT) Apply-Orbit-File -Ssource=target_split.dim -t target_orb
	rm -rf target_split.dim target_split.data

# Deburst
# target_deburst.dim: target_split.dim
target_deburst.dim: target_orb.dim
	$(GPT) TOPSAR-Deburst -SsourceProduct=target_orb.dim -t target_deburst.dim -c 1024M -q 1 
	rm -rf target_orb.dim target_orb.data

# Range Doppler Terrain: cf qgis for map projection
$(FILENAME1).dim: target_deburst.dim
	$(GPT) Terrain-Correction -SsourceProduct=target_deburst.dim -PdemName="External DEM" -PexternalDEMFile="./clipped_DEM.tif" -PexternalDEMNoDataValue=0.0 -PmapProjection="EPSG:32633" -PapplyRadiometricNormalization=true -t target_final.dim
	mv target_final.dim $(FILENAME1).dim
	mv target_final.data $(FILENAME1).data
	rm -rf target_deburst.dim target_deburst.data

clean:
	rm -rf target*
